name: DockerImage build
on:
  push:
    branches:
      - main
      - bre*
    tags:
      - v*
  pull_request:
    branches:
      - main
jobs:
  build_image:
    permissions: write-all
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: docker-ci:1.0.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - uses: actions/setup-node@v4
        with:
          node-version: v20.11.0
      - name: Build Docker Image
        run: |
          docker image build --tag="${IMAGE_NAME}" ./
      - name: Launch npm run lint in a container / in a volume
        run: |
            docker container run --workdir="$(pwd)" --volume="$(pwd)":"$(pwd)"  "${IMAGE_NAME}" npm run lint
        continue-on-error: true
      - name: Run Docker container and curl command
        run: |
          docker run -d --name test-container ${IMAGE_NAME} node index.js
          sleep 5
          docker exec test-container curl http://localhost:3000
          docker stop test-container
      - name: Remove Docker Container
        run: |
          docker rm -f test-container
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image if push on main branch
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          context: ./
          tags: bertrand2808/docker-ci:latest
      - name: Push Docker Image if push on tag
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: ./
          tags: bertrand2808/docker-ci:${{ github.ref_name }}
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this New Release :
          draft: false
          prerelease: false


