name: DockerImage build
on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]
jobs:
  build_image:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: docker-ci:1.0.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - uses: actions/setup-node@v4
        with:
          node-version: v20.11.0
      - name: Launch npm run lint in a container / in a volume
        run: |
            docker container run --workdir="$(pwd)" --volume="$(pwd)":"$(pwd)"  "${IMAGE_NAME}" npm run lint
      - name: Build Docker Image
        run: |
          docker image build --tag="${IMAGE_NAME}" ./
      - name: Run Docker container
        run: |
          docker run -d --name test-container ${IMAGE_NAME} node index.js
          sleep 5
          docker exec test-container curl http://localhost:3000
          docker stop test-container
      - name: Remove Docker Container
        run: |
          docker rm -f test-container
